import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { pathToFileURL } from 'url';
import { Lexer, Parser } from '../parser';
import { Analyzer, Scope } from '../analyzer';
import { ALL_SOURCES } from './decls';

const BANNER = [
  '// =========================================================================',
  '// Echo AngelScript API -- bundled declaration file',
  '//',
  '// This file is regenerated by the language server on every restart.',
  '// Edits made here are NOT preserved and have no effect on the IDE.',
  '// =========================================================================',
  '',
].join('\n');

/**
 * Parses every bundled API `.as` declaration into a single read-only API
 * scope and writes each source to a temp directory so go-to-definition can
 * jump there.
 *
 * Mount the returned scope as the parent of every user module's global
 * scope so API symbols are visible via the normal scope walk.
 */
export function loadApiScope(): Scope {
  const baseDir = path.join(os.tmpdir(), 'echo-angelscript-lsp', 'api');

  const apiScope = new Scope('global', null, { start: 0, end: 0 });
  apiScope.external = true;

  for (const [name, source] of ALL_SOURCES) {
    const onDiskSource = BANNER + source;
    const filePath = path.join(baseDir, name);
    let sourceUri: string;
    try {
      fs.mkdirSync(path.dirname(filePath), { recursive: true });
      fs.writeFileSync(filePath, onDiskSource);
      sourceUri = pathToFileURL(filePath).toString();
    } catch (e) {
      // eslint-disable-next-line no-console
      console.error(`Failed to write API '${name}' to disk:`, e);
      sourceUri = '';
    }

    try {
      const { tokens, docs } = new Lexer(onDiskSource).tokenize();
      const { module, errors } = new Parser(tokens, docs).parse();
      if (errors.length > 0) {
        // eslint-disable-next-line no-console
        console.error(`API '${name}' has ${errors.length} parse error(s); first: ${errors[0].message}`);
      }
      new Analyzer(sourceUri || undefined).analyzeInto(module, apiScope);
    } catch (e) {
      // eslint-disable-next-line no-console
      console.error(`Failed to load API '${name}':`, e);
    }
  }

  return apiScope;
}
